# Generated by Django 3.1 on 2020-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20200816_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='applied_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
    ]
