# Generated by Django 3.1 on 2020-08-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_for',
        ),
    ]
