# Generated by Django 3.1 on 2020-08-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('announcement', '0006_remove_notice_notice_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='notice_for',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
