# Generated by Django 3.1 on 2020-08-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_auto_20200830_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_for',
        ),
    ]
