# Generated by Django 3.1 on 2020-08-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_hostelstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoomAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.IntegerField(blank=True, null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
