# Generated by Django 3.1 on 2020-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0014_hostelroomassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ManyToManyField(blank=True, to='hostels.Hostel'),
        ),
    ]
