# Generated by Django 3.1 on 2020-08-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0016_auto_20200817_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostel',
            name='room',
            field=models.ManyToManyField(blank=True, to='hostels.Room'),
        ),
    ]
