# Generated by Django 3.1 on 2020-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0017_auto_20200818_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelroomstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hostelstaff',
            name='user',
        ),
    ]
