# Generated by Django 3.1 on 2020-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200831_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='is_permanent',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
