# Generated by Django 3.1 on 2020-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20200901_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Select '), ('1', 'Male'), ('2', 'female'), ('3', 'Others')], max_length=5, null=True),
        ),
    ]
