# Generated by Django 3.1 on 2020-08-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0009_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
