# Generated by Django 3.1 on 2020-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0010_auto_20200830_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='complain_by',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='meet_user',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='meet_user_type',
        ),
    ]
