# Generated by Django 3.1 on 2020-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_monthly_income', models.FloatField(blank=True, max_length=255, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('father_nid', models.IntegerField(blank=True, max_length=255, null=True)),
                ('father_passport', models.CharField(blank=True, max_length=255, null=True)),
                ('father_license', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_monthly_income', models.FloatField(blank=True, max_length=255, null=True)),
                ('mother_educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mother_nid', models.IntegerField(blank=True, max_length=255, null=True)),
                ('mother_passport', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_license', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
