# Generated by Django 3.1 on 2020-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_nid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_nid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
