# Generated by Django 3.1 on 2020-08-29 07:42

from django.db import migrations, models
import libraries.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0018_auto_20200829_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[libraries.models.validate_image]),
        ),
    ]
