# Generated by Django 3.1 on 2020-09-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
    ]
