# Generated by Django 3.1 on 2020-09-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_subject_subject_class'),
        ('exam', '0002_auto_20200903_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.section'),
        ),
    ]
