# Generated by Django 3.1 on 2020-09-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='ca_number',
            new_name='mcq_mark',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='cr_number',
            new_name='pass_mark',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='msq_number',
            new_name='practical_mark',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='pr_number',
            new_name='viva_mark',
        ),
        migrations.AddField(
            model_name='result',
            name='written_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
