# Generated by Django 3.1 on 2020-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_result_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='class_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='mcq_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='pass_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='practical_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_roll',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='viva_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='written_mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
