# Generated by Django 3.1 on 2020-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_result_cr_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('mark_from', models.IntegerField(blank=True, null=True)),
                ('mark_to', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
