# Generated by Django 3.1 on 2020-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20200907_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='day',
        ),
        migrations.AddField(
            model_name='routine',
            name='day',
            field=models.ManyToManyField(null=True, related_name='day', to='routine.Day'),
        ),
    ]
