# Generated by Django 3.1 on 2020-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20200907_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='day',
        ),
        migrations.AddField(
            model_name='routine',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
