# Generated by Django 3.1 on 2020-09-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_auto_20200903_1631'),
        ('teacher', '0005_auto_20200906_1823'),
        ('routine', '0005_auto_20200908_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routine',
            new_name='TimeTableItem',
        ),
    ]
