# Generated by Django 3.1 on 2020-09-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0011_auto_20200903_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('note', models.TextField(null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
