# Generated by Django 3.1 on 2020-09-08 06:17

from django.db import migrations, models
import syllabus.models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20200908_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(null=True, upload_to='ebook', validators=[syllabus.models.validate_file]),
        ),
    ]
