# Generated by Django 3.1 on 2020-09-06 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.CharField(blank=True, max_length=100, null=True)),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
