# Generated by Django 3.1 on 2020-08-15 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email_1', models.EmailField(max_length=100, unique=True)),
                ('email_2', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('serial_no', models.IntegerField(unique=True)),
                ('website', models.URLField(max_length=100, unique=True)),
                ('institute_code', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=10)),
                ('address_1', models.CharField(max_length=500)),
                ('address_2', models.CharField(blank=True, max_length=500, null=True)),
                ('established_date', models.DateField()),
                ('phone_1', models.CharField(max_length=15, unique=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('active_status', models.IntegerField()),
                ('agree', models.BooleanField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'institute',
            },
        ),
    ]
