# Generated by Django 3.1 on 2020-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20200815_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='active_status',
            field=models.IntegerField(choices=[('1', 'Active'), ('2', 'InActive')], default=1),
        ),
    ]
