# Generated by Django 3.1 on 2020-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20200816_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'InActive')], default=1, max_length=10),
        ),
    ]
