# Generated by Django 3.1 on 2020-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20200816_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='active_status',
            field=models.CharField(choices=[('0', 'Select'), ('1', 'Active'), ('2', 'InActive')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='email_1',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='email_2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='principal_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
