# Generated by Django 3.1 on 2020-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20200817_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='principal_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads'),
        ),
    ]
