# Generated by Django 3.1 on 2020-08-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_auto_20200818_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.city'),
        ),
        migrations.AddField(
            model_name='institute',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.country'),
        ),
        migrations.AddField(
            model_name='institute',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.state'),
        ),
    ]
