# Generated by Django 3.1 on 2020-08-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_auto_20200818_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
