# Generated by Django 3.1 on 2020-08-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_auto_20200818_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
