# Generated by Django 3.1 on 2020-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_auto_20200818_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso',
            new_name='capital',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numcode',
            new_name='wikiDataId',
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='emoji',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='emojiU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='native',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
