# Generated by Django 3.1 on 2020-08-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_auto_20200818_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='nicename',
        ),
    ]
