# Generated by Django 3.1 on 2020-08-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_remove_country_nicename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='capital',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='created_at',
            new_name='nicename',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='wikiDataId',
            new_name='numcode',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='country',
            name='emojiU',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='native',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
    ]
