# Generated by Django 3.1 on 2020-08-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0021_auto_20200819_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='fips_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='flag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='iso2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='wikiDataId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
