# Generated by Django 3.1 on 2020-08-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0022_auto_20200819_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='wikiDataId',
            new_name='wikiData',
        ),
    ]
