# Generated by Django 3.1 on 2020-08-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0024_auto_20200819_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso',
            new_name='sortname',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='country',
            name='nicename',
        ),
        migrations.RemoveField(
            model_name='country',
            name='numcode',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='fips_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='state',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='state',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='wiki',
        ),
    ]
