# Generated by Django 3.1 on 2020-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0026_auto_20200819_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
