# Generated by Django 3.1 on 2020-08-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0027_institute_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='date',
        ),
    ]
