# Generated by Django 3.1 on 2020-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0028_remove_institute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
