# Generated by Django 3.1 on 2020-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0029_institute_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
