# Generated by Django 3.1 on 2020-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0031_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
