# Generated by Django 3.1 on 2020-08-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0046_auto_20200826_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='agree',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
