# Generated by Django 3.1 on 2020-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0048_auto_20200827_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='established_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
