# Generated by Django 3.1 on 2020-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0009_auto_20200813_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemember',
            name='user',
        ),
    ]
