# Generated by Django 3.1 on 2020-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='designation',
            field=models.CharField(choices=[('1', 'সভাপতি'), ('1', 'অধ্যক্ষ/সচিব'), ('1', 'সম্পাদক'), ('1', 'বিদ্যুৎসাহী'), ('1', 'দাতা সদস্য'), ('1', 'অভিভাবক সদস্য'), ('1', 'শিক্ষক প্রতিনিধি')], max_length=2),
        ),
    ]
