# Generated by Django 3.1 on 2020-08-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitee', '0003_commitee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitee',
            name='created_at',
        ),
    ]
